openrepairplatform/event/urls.py
from django.urls import path

from . import views
from openrepairplatform.mixins import CreateMembershipMixin, UpdateMembershipMixin

app_name = "event"


urlpatterns = [
    path(
        "future_event_place_autocomplete/",
        views.FutureEventPlaceAutocomplete.as_view(),
        name="future_event_place_autocomplete",
    ),
    path(
        "future_event_activity_autocomplete/",
        views.FutureEventActivityAutocomplete.as_view(),
        name="future_event_activity_autocomplete",
    ),
    path(
        "<str:orga_slug>/condition_orga_autocomplete/",
        views.ConditionOrgaAutocomplete.as_view(),
        name="condition_orga_autocomplete",
    ),
    path(
        "condition/create/<int:orga_pk>/",
        views.ConditionCreateView.as_view(),
        name="condition_create",
    ),
    path(
        "condition/<int:pk>/edit/",
        views.ConditionEditView.as_view(),
        name="condition_edit",
    ),
    path(
        "condition/<int:pk>/delete/",
        views.ConditionDeleteView.as_view(),
        name="condition_delete",
    ),
    path("activity/", views.ActivityListView.as_view(), name="activity_list"),
    path(
        "activity/create/<int:orga_pk>/",
        views.ActivityCreateView.as_view(),
        name="activity_create",
    ),
    path(
        "activity/<int:pk>/edit/",
        views.ActivityEditView.as_view(),
        name="activity_edit",
    ),
    path(
        "activity/<int:pk>/delete/",
        views.ActivityDeleteView.as_view(),
        name="activity_delete",
    ),
    path(
        "activity/<int:pk>/<slug>/",
        views.ActivityView.as_view(),
        name="activity_detail",
    ),
    path("", views.EventListView.as_view(), name="list"),
    path("create/<int:orga_pk>/", views.EventCreateView.as_view(), name="create"),
    path(
        "recurrent/create/<int:orga_pk>/",
        views.RecurrentEventCreateView.as_view(),
        name="recurrent_create",
    ),
    path("<int:pk>/edit/", views.EventEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.EventDeleteView.as_view(), name="delete"),
    # path("<int:pk>/close/", views.CloseEventView.as_view(), name="close"),
    path(
        "<int:pk>/add_active/",
        views.AddActiveEventView.as_view(),
        name="add_active",
    ),
    path(
        "<int:pk>/remove_active/",
        views.RemoveActiveEventView.as_view(),
        name="remove_active",
    ),
    path("<int:pk>/<slug>/", views.EventView.as_view(), name="detail"),
    path("<int:pk>/<slug>/admin/", views.EventAdminView.as_view(), name="detail_admin"),
    path(
        "<int:pk>/<slug>/book/<int:user_pk>",
        views.EventBookStuffView.as_view(),
        name="book_confirm",
    ),
    path(
        "<int:pk>/add_stuff/<int:user_pk>",
        views.EventAddStuffView.as_view(),
        name="add_stuff_event",
    ),
    path(
        "create_stuff/<int:event_pk>/<int:registered_pk>",
        views.StuffUserEventFormView.as_view(),
        name="create_user_event_stuff",
    ),
    path(
        "create_stuff_orga/<int:event_pk>/<int:registered_pk>",
        views.StuffUserOrgaEventFormView.as_view(),
        name="create_user_event_stuff_orga",
    ),
    path(
        "cancel_reservation/<token>/",
        views.CancelReservationView.as_view(),
        name="cancel_reservation",
    ),
    path("book/<token>/", views.BookView.as_view(), name="book"),
    path("absent/<token>/", views.AbsentView.as_view(), name="user_absent"),
    path("present/<token>/", views.PresentView.as_view(), name="user_present"),
    path(
        "add-to-member/<int:pk>/<int:event_pk>/",
        CreateMembershipMixin.as_view(),
        name="add_member",
    ),
    path(
        "update-member/<int:orga_pk>/<int:pk>/<int:event_pk>/",
        UpdateMembershipMixin.as_view(),
        name="update_member",
    ),
    path(
        "add-participation/<int:user_pk>/<int:event_pk>/",
        views.ParticipationCreateView.as_view(),
        name="add_participation",
    ),
    path(
        "update-participation/<int:pk>/",
        views.ParticipationUpdateView.as_view(),
        name="update_participation",
    ),
    path(
        "delete-participation/<int:pk>/",
        views.ParticipationDeleteView.as_view(),
        name="delete_participation",
    ),
    path(
        "ical-event/<int:pk>/",
        views.EventICSView.as_view(),
        name="ical_event",
    ),
    path(
        "ical-events/<int:pk>/",
        views.EventByOrganizationICSView.as_view(),
        name="ical_events",
    ),
    path(
        "invitation/<token>/",
        views.InvitationFormView.as_view(),
        name="invitation",
    ),
]

openrepairplatform/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

import debug_toolbar

from . import views
from openrepairplatform.inventory.views import OrganizationStockView


urlpatterns = [
    # View test vuejs
    path("", views.HomeView.as_view(), name="homepage"),
    path(
        "mentions-legales/",
        views.MentionsView.as_view(),
        name="mentions-legales",
    ),
    path(
        "a-propos/",
        views.AboutView.as_view(),
        name="a-propos",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("where/", views.LocaliseRedirect.as_view(), name="where"),
    path("user/", include("openrepairplatform.user.urls", namespace="user")),
    path("avatar/", include("initial_avatars.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("event/", include("openrepairplatform.event.urls", namespace="event")),
    path(
        "inventory/",
        include("openrepairplatform.inventory.urls", namespace="inventory"),
    ),
    path(
        "location/",
        include("openrepairplatform.location.urls", namespace="location"),
    ),
    path(
        "api/location/",
        include("openrepairplatform.location.api_urls", namespace="api_location"),
    ),
    
    path(
        "api/user/",
        include("openrepairplatform.user.api_urls", namespace="api_user"),
    ),
    path(
        "api/event/",
        include("openrepairplatform.event.api_urls", namespace="api_event"),
    ),
    path(
        "place_autocomplete/",
        views.PlaceAutocomplete.as_view(),
        name="place_autocomplete",
    ),
    path(
        "activity_autocomplete/",
        views.ActivityAutocomplete.as_view(),
        name="activity_autocomplete",
    ),
    path(
        "user_autocomplete/",
        views.CustomUserAutocomplete.as_view(),
        name="user_autocomplete",
    ),
    path(
        "<str:orga_slug>/user_orga_autocomplete/",
        views.ActiveOrgaAutocomplete.as_view(),
        name="user_orga_autocomplete",
    ),
    path(
        "<str:orga_slug>/",
        views.OrganizationPageView.as_view(),
        name="organization_page",
    ),
    path(
        "<str:orga_slug>/groups/",
        views.OrganizationGroupsView.as_view(),
        name="organization_groups",
    ),
    path(
        "<str:orga_slug>/members/",
        views.OrganizationMembersView.as_view(),
        name="organization_members",
    ),
    path(
        "<str:orga_slug>/details/",
        views.OrganizationDetailsView.as_view(),
        name="organization_details",
    ),
    path(
        "<str:orga_slug>/controls/",
        views.OrganizationControlsView.as_view(),
        name="organization_controls",
    ),
    path(
        "<str:orga_slug>/events/",
        views.OrganizationEventsView.as_view(),
        name="organization_events",
    ),
    path(
        "<str:orga_slug>/stock/",
        OrganizationStockView.as_view(),
        name="organization_stock",
    ),
    path(
        "<str:orga_slug>/accounting/",
        views.OrganizationFeesView.as_view(),
        name="organization_fees",
    ),
    
    path(r"tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))] 

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openrepairplatform/event/models.py
from datetime import date, datetime, timedelta

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords

from openrepairplatform.fields import CleanHTMLField

from openrepairplatform.location.models import Place
from openrepairplatform.user.models import CustomUser, Organization
from openrepairplatform.utils import get_future_published_events, validate_image
from openrepairplatform.inventory.models import Stuff


class Condition(models.Model):
    name = models.CharField(verbose_name=_("Condition Type"), max_length=100)
    description = models.CharField(
        verbose_name=_("Condition description"), default="", max_length=300
    )
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="conditions"
    )
    price = models.FloatField(verbose_name=_("Price"), default=5)
    history = HistoricalRecords()

    def get_absolute_url(self):
        return reverse(
            "organization_page",
            kwargs={"orga_slug": self.organization.slug},
        )

    def __str__(self):
        if self.price > 0:
            return f"{self.name} - {self.price}€"
        return self.name


class ActivityCategory(models.Model):
    name = models.CharField(verbose_name=_("Activity type"), max_length=100)
    slug = models.SlugField(blank=True)
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Activity(models.Model):
    name = models.CharField(verbose_name=_("Activity type"), max_length=100)
    category = models.ForeignKey(
        ActivityCategory,
        related_name="category",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    slug = models.SlugField(blank=True)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="activities"
    )
    description = CleanHTMLField(verbose_name=_("Activity description"), default="")
    picture = models.ImageField(
        verbose_name=_("Image"),
        upload_to="activities/",
        blank=True,
        null=True,
        validators=[validate_image],
    )
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("event:activity_detail", args=(self.pk, self.slug))

    def next_events(self):
        return get_future_published_events(self.events)[0:3]

    class Meta:
        verbose_name_plural = 'Activities'

class Event(models.Model):
    WEEKS = [
        (1, "Semaine 1"),
        (2, "Semaine 2"),
        (3, "Semaine 3"),
        (4, "Semaine 4"),
        (5, "Semaine 5"),
    ]
    DAYS = [
        ("MO", "Lundi"),
        ("TU", "Mardi"),
        ("WE", "Mercredi"),
        ("TH", "Jeudi"),
        ("FR", "Vendredi"),
        ("SA", "Samedi"),
        ("SU", "Dimanche"),
    ]

    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="events"
    )
    conditions = models.ManyToManyField(
        Condition,
        related_name="events",
        verbose_name=_("Conditions"),
        blank=True,
    )
    published = models.BooleanField(
        verbose_name=_("Published"),
        default=False,
    )
    publish_at = models.DateTimeField(
        verbose_name=_("Publication date and time"), default=timezone.now
    )
    activity = models.ForeignKey(
        Activity, on_delete=models.SET_NULL, null=True, related_name="events"
    )
    description = CleanHTMLField(
        verbose_name=_(
            "Description supplémentaire de l'événément "
            "(remplace la définition par défaut de l'activité)"
        ),
        blank=True,
    )
    collaborator = models.CharField(
        verbose_name=_("En association avec"), max_length=100, blank=True
    )
    external = models.BooleanField(
        verbose_name=_("Réservation externe au site ?"), default=False
    )
    external_url = models.URLField(
        max_length=200,
        verbose_name=_(
            "Lien vers un site externe. Pour la réservation externe "
            "(si activée) ou simplement pour info"
        ),
        blank=True,
    )
    members_only = models.BooleanField(default=True, blank=True)
    slug = models.SlugField(blank=True)
    date = models.DateField(verbose_name=_("Jour"), default=date.today)
    starts_at = models.TimeField(verbose_name=_("Heure de début"), default=timezone.now)
    ends_at = models.TimeField(verbose_name=_("Heure de fin"))
    available_seats = models.PositiveIntegerField(
        verbose_name=_("Places disponibles"), default=0
    )
    registered = models.ManyToManyField(
        CustomUser,
        related_name="registered_events",
        verbose_name=_("Utilisateurs attendus"),
        blank=True,
    )
    presents = models.ManyToManyField(
        CustomUser,
        related_name="presents_events",
        verbose_name=_("Presents"),
        blank=True,
        through="Participation",
    )
    needed_organizers = models.PositiveIntegerField(
        verbose_name=_("Nombre d'animateurs attendus"), default=0
    )
    organizers = models.ManyToManyField(
        CustomUser,
        related_name="organizers_events",
        verbose_name=_("Organisateurs / animateurs "),
        blank=True,
    )
    location = models.ForeignKey(
        Place,
        on_delete=models.SET_NULL,
        null=True,
        related_name="events",
        verbose_name="Lieu",
    )
    allow_stuffs = models.BooleanField(
        verbose_name=_("Souhaitez-vous gérer des réparations électroniques ?"),
        default=False,
        blank=True,
        help_text=(
            "Les participants pourront déclarer leurs objets électroniques à réparer "
            "lors de la réservation"
        ),
    )
    stuffs = models.ManyToManyField(
        Stuff,
        verbose_name=_("Objets attendus"),
        related_name="events",
        blank=True,
    )
    is_free = models.BooleanField(
        default=False, verbose_name=_("Pas de limite de place ?")
    )
    booking = models.BooleanField(
        default=False, verbose_name=_("Réservation nécessaire ?")
    )
    internal_notes = CleanHTMLField(
        verbose_name= _("Notes de l'évènement visibles en interne"),
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        if self.activity:
            slug = self.activity.name
        else:
            slug = "no activity type"
        self.slug = slugify(slug)
        return super().save(*args, kwargs)

    @property
    def remaining_seats(self):
        return self.available_seats - self.registered.count()

    def date_interval_format(self):
        date = self.date.strftime("%A %d %B")
        starts_at_time = self.starts_at.strftime("%H:%M")
        ends_at_time = self.ends_at.strftime("%H:%M")

        # ex Lundi 01 Janvier 2018 de 20:01:12 à 22:01:12
        return f"{date} de {starts_at_time} à {ends_at_time}"

    def get_absolute_url(self):
        return reverse("event:detail", args=(self.pk, self.slug))

    @property
    def has_ended(self):
        ends = datetime.combine(
            self.date, self.ends_at, tzinfo=timezone.now().tzinfo
        ) + timedelta(hours=4)
        return ends < timezone.now()

    @property
    def has_started(self):
        starts = datetime.combine(
            self.date, self.starts_at, tzinfo=timezone.now().tzinfo
        ) - timedelta(hours=2)
        return starts < timezone.now()

    @classmethod
    def future_published_events(cls):
        return get_future_published_events(cls.objects)

    def __str__(self):
        if self.activity:
            activity_name = self.activity.name
        else:
            activity_name = "no activity type"
        full_title = "%s du %s" % (
            activity_name,
            self.date.strftime("%d %B"),
        )
        return full_title


class Participation(models.Model):
    PAYMENT_CASH = "1"
    PAYMENT_BANK = "2"
    PAYMENT_BANK_CHECK = "3"
    PAYMENT_CB = "4"
    PAYMENT_LOCAL_CASH = "5"
    PAYMENTS = (
        (PAYMENT_CASH, _("Espèces")),
        (PAYMENT_BANK, _("En ligne")),
        (PAYMENT_BANK_CHECK, _("Chèque")),
        (PAYMENT_CB, _("CB")),
        (PAYMENT_LOCAL_CASH, _("Monnaie locale")),
    )
    payment = models.CharField(
        max_length=1, choices=PAYMENTS, blank=True, default=PAYMENT_CASH
    )
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name="participations"
    )
    amount = models.PositiveIntegerField(
        verbose_name=_("Montant payé"), default=0, blank=True
    )
    history = HistoricalRecords()

    class Meta:
        unique_together = (("user", "event"),)

    def __str__(self):
        return " Participation " + self.user.first_name + " " + str(self.event)

    def get_absolute_url(self):
        return reverse("event:detail", args=(self.event.pk, self.event.slug))

openrepairplatform/event/templates/event/book_confirm_add_stuff.html
{% load assets app_filters thumbnail bootstrap5 static %}

<div class="modal fade" tabindex="-1" role="dialog" data-bs-focus="false" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<div class="pt-2">
  <div class="">
    <h5 class="text-success">
      <i class="mt-2 far fa-hand-peace fa-3x"></i> Réservation confirmée !
    </h5>
  </div>
  <span class="mt-2 d-block mb-2">
    <i class="text-danger">Noubliez-pas : réserver une place vous engage à participer.</i>
  </span>
  <a class="btn btn-light" href="{% url 'event:ical_event' event.pk %}">
    <i class="far fa-calendar-plus"></i> ajouter à mon agenda
  </a>
  {% if event.allow_stuffs %}
    <div class="mt-2 mb-2 text-center">
      <span class="m-2"><b>Optionnel</b> Dites-nous quel objet vous apportez.</span><br>
      <small> Sélectionner un objet dans votre inventaire ci-dessous, ou 
        <a class="bs-gobal-modal" href="#" data-form-url="{% url 'event:create_user_event_stuff' event.pk user_success_booking.pk %}">
          créez-en un nouveau 
        </a> puis selectionnez-le 
      </small>
        {% if user_success_booking.user_stuffs %}
          <div class="mb-4">
            <div class="mt-2 shadow-sm">
              <form method="POST" action="{% url 'event:add_stuff_event' event.pk user_success_booking.pk %}">
                {% csrf_token %}
              <div class="table-responsive bordered">
                <table class="table mb-0 text-left" if="stuffs-table">
                  <thead>
                    <tr>
                      <th colspan="2">Mon inventaire</th>
                      <th>Sélectionner</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                    <td colspan="3" class="text-center">
                      <a class="bs-gobal-modal" href="#" data-form-url="{% url 'event:create_user_event_stuff' event.pk user_success_booking.pk %}">
                        créer un autre objet
                      </a>
                    </td>
                    </tr>
                      {% for stuff in user_success_booking.user_stuffs.all %}
                      <tr>
                        <td scope="row" colspan="2">{{ stuff }}</td>
                        <td class="text-right">
                          <input class="form-check-input position-static" type="radio" name="selectedstuff" value='{{stuff.pk|cut:" "}}'>
                        </td>
                      </tr>
                      {% empty %}
                      <tr>
                        <td colspan="3">
                        Cet utilisateur n'a pas d'objet dans son inventaire
                        </td>
                      </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <button type="submit" disabled=true id="submitStuff" class="btn mt-2 btn-light w-100 p-1">Valider mon choix</button>
              </form>
            </div>
          </div>
          {% endif %}
        </div>
      {% endif %}
      {% if event.allow_stuffs %}
      <a class="d-block btn mt-2 btn-light w-100 p-3" href="{{ event.get_absolute_url }}">Passer l'étape</a>
      {% else %}
      <a class="d-block btn mt-4 btn-light w-100 p-3" id="close" href="{{ event.get_absolute_url }}">Fermer</a>
      Retour automatique dans <span class="c" id="10"></span>
      {% endif %}
  </div>
{% block extra_js %}
  <script type="text/javascript">
    $(document).ready(function(){
    $radio = $("input:radio[name='selectedstuff']")
    $radio.change(function(){
    if ($radio.is(':checked')) {
      $("#submitStuff").removeAttr("disabled");
    }
    })
  
    window.onload = function() {
    {% if not event.allow_stuffs %}
    setTimeout(function() {
    document.getElementById('close').click();
    }, 7000);
    {% endif %}
    };
    {% if not event.allow_stuffs %}
    function c(){3000
    var n=$('.c').attr('id');
    var c=n;
    $('.c').text(c);
    setInterval(function(){
        c--;
        if(c>=0){
            $('.c').text(c);
        }
        if(c==0){
            $('.c').text(n);
        }
    },1000);
    }
    // Start
    c();
    // Loop
    setInterval(function(){
        c();
    },5000);
    {% endif %}
  });
  </script>
{% endblock %}

openrepairplatform/event/templates/event/event_detail.html
{% extends 'base.html' %}
{% load assets l10n app_filters static %}
{% load thumbnail %}
{% block title %}{{ event }}{% endblock %}
{% block extra_css %}
  {% assets "css_detail_event" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet" />
  {% endassets %}
{% endblock %}
{% block content %}
  <!-- Modals -->
  <div class="modal fade" tabindex="-1" role="dialog" data-bs-focus="false" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
  <!-- Breadcrumb -->
  {% url "event:list" as event_list_url %}
  {% include "breadcrumb.html" with current=event first_parent_url=event_list_url first_parent_text="Évènements" %}
  <!-- Event header -->
  <div id="header-event-detail"
       style="background-image:url('{% if event.activity.picture and event.activity.picture.url %}{{ event.activity.picture.url }}{% endif %}')">
    <div class="container d-flex" style="height:200px;">
      <div class="d-flex align-items-end">
        {% url 'event:detail_admin' slug=event.slug pk=event.pk as the_url %}
        {% if is_active %}
          {% if request.get_full_path == the_url %}
            <a href="{{ event.get_absolute_url }}"
               class="btn btn-large btn-light me-2 mb-2 ">Ne plus administrer</a>
            {% include "event/invitation.html" %}
          {% else %}
            <a href="admin" class="btn btn-large btn-light me-2 mb-2 ">
              <i class="fas fa-cog"></i>   Administrer
            </a>
          {% endif %}
        {% endif %}
      </div>
      <div class="d-flex align-items-end">
        {% if request.get_full_path != the_url %}
          <a class="btn btn-light me-2 mb-2 "
             href="{% url 'event:ical_event' event.pk %}">
            <i class="far fa-calendar-plus"></i> ajouter à mon agenda
          </a>
        {% endif %}
      </div>
    </div>
  </div>
  {% if is_active %}
    {% url 'event:detail_admin' slug=event.slug pk=event.pk as the_url %}
    {% if request.get_full_path == the_url %}
      {% block admin %}
      {% endblock admin %}
    {% else %}
      {% include "event/detail/event_detail_visitor.html" %}
    {% endif %}
  {% else %}
    {% include "event/detail/event_detail_visitor.html" %}
  {% endif %}
{% endblock %}
{% block extra_js %}
    {% assets "js_create_stuff" %}
        <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
   <script>
  if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){

    $("#event-book").unstick()
    $(".event-book").addClass("event-book-mobile")
    {% if user_success_booking %}
      $(".event-book").addClass("event-book-mobile-show")
      $("#book_show").html("Réservation confirmée")
    {% endif %}

    function display_book(){
      if($(".event-book").hasClass("event-book-mobile-show")){
        $(".event-book").removeClass("event-book-mobile-show")
      }
      else {
        $(".event-book").addClass("event-book-mobile-show")
      }
    };
  }
  </script>
{% endblock extra_js %}

openrepairplatform/event/templates/event/participation_form.html
{% load bootstrap5 app_filters %}

<div class="modal" aria-bs-hidden="true" data-bs-focus="false" id="participation-{{ user.pk|escape }}" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          Participation
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body text-center">
        {% if participation %}
          <form class="d-inline" action="{% url 'event:delete_participation' participation.pk %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Supprimer</button>
          </form>
        {% endif %}
        <form action="{% if participation %}{% url 'event:update_participation' participation.pk %}{% else %}{% url 'event:add_participation' user.pk event.pk %}{% endif %}"
              method="post"
              class="text-left">
          <div class="modal-body">
            {% csrf_token %}
            {% bootstrap_form form=form %}
          </div>
          <div class="modal-footer">
            <input type="submit" value="Enregistrer" class="btn btn-primary">
          </div>
        </form>
      </div>

    </div>
  </div>
</div>

openrepairplatform/event/templates/event/register.html
{% load app_filters bootstrap5 %}
{% if admin_text or not request.user.is_authenticated %}
  {% if event.booking == False %}
    <a class="btn btn-outline-warning">Événement sans réservation</a>
  {% else %}
    {% if admin_text %}
      <button class="btn btn-success rounded-circle">

        <i class="fa fa-plus"></i>
      </button>
      {{ admin_text }}
    {% else %}
      {% if event.remaining_seats > 0 or event.is_free %}
        <form action="{% url 'user:create_and_book' %}?event={{ event.pk | slugify }}"
              method="post">
          {% csrf_token %}
          {% bootstrap_form form=register_form %}
          <div class="modal-footer">
            <input type="submit"
                   value="Participer"
                   class="btn btn btn-success btn-block" />
          </div>
        </form>
      {% else %}
        <a class="btn btn-block btn-outline-danger">Complet</a>
      {% endif %}
    {% endif %}

  {% endif %}
{% else %}
  {% if event.booking == False %}
    <a class="btn btn-outline-warning">Événement sans réservation</a>
  {% elif event.booking == True and event.remaining_seats > 0 or event.is_free %}
    {% if request.user not in event.registered.all and request.user not in event.organizers.all %}
      {% tokenize user=request.user event=event action='book' as tok %}
      <a href="{% url 'event:book' tok %}" class="btn btn-block btn-secondary">Je participe !</a>
    {% elif request.user in event.organizers.all %}
      <a class="btn btn-outine-danger">J'anime cet évènement</a>
    {% endif %}
  {% else %}
    <a class="btn btn-block btn-outline-danger">Complet</a>
  {% endif %}
  {% if request.user in event.registered.all %}
    {% if request.user in event.presents.all %}
      <h4 class="text-center">Vous ne pouvez plus annuler car vous avez été noté présent</h4>
    {% else %}
      {% tokenize user=request.user event=event action='cancel' as tok %}
      <br>
      <h4 class="text-center">Vous participez à cet événement</h4>
      <a href="{% url 'event:cancel_reservation' tok %}"
         class="btn btn-block btn-danger">Je ne participe plus</a>
    {% endif %}
  {% endif %}
{% endif %}
{% block extra_js %}
  <script>
  $(document).ready(function(){
    $(".booking_form").click(function() {
      $("#reservation{{ event.pk }}").insertBefore(".header");
});
  });
  </script>
{% endblock extra_js %}