openrepairplatform/event/urls.py
from django.urls import path

from . import views
from openrepairplatform.mixins import CreateMembershipMixin, UpdateMembershipMixin

app_name = "event"


urlpatterns = [
    path(
        "future_event_place_autocomplete/",
        views.FutureEventPlaceAutocomplete.as_view(),
        name="future_event_place_autocomplete",
    ),
    path(
        "future_event_activity_autocomplete/",
        views.FutureEventActivityAutocomplete.as_view(),
        name="future_event_activity_autocomplete",
    ),
    path(
        "<str:orga_slug>/condition_orga_autocomplete/",
        views.ConditionOrgaAutocomplete.as_view(),
        name="condition_orga_autocomplete",
    ),
    path(
        "condition/create/<int:orga_pk>/",
        views.ConditionCreateView.as_view(),
        name="condition_create",
    ),
    path(
        "condition/<int:pk>/edit/",
        views.ConditionEditView.as_view(),
        name="condition_edit",
    ),
    path(
        "condition/<int:pk>/delete/",
        views.ConditionDeleteView.as_view(),
        name="condition_delete",
    ),
    path("activity/", views.ActivityListView.as_view(), name="activity_list"),
    path(
        "activity/create/<int:orga_pk>/",
        views.ActivityCreateView.as_view(),
        name="activity_create",
    ),
    path(
        "activity/<int:pk>/edit/",
        views.ActivityEditView.as_view(),
        name="activity_edit",
    ),
    path(
        "activity/<int:pk>/delete/",
        views.ActivityDeleteView.as_view(),
        name="activity_delete",
    ),
    path(
        "activity/<int:pk>/<slug>/",
        views.ActivityView.as_view(),
        name="activity_detail",
    ),
    path("", views.EventListView.as_view(), name="list"),
    path("create/<int:orga_pk>/", views.EventCreateView.as_view(), name="create"),
    path(
        "recurrent/create/<int:orga_pk>/",
        views.RecurrentEventCreateView.as_view(),
        name="recurrent_create",
    ),
    path("<int:pk>/edit/", views.EventEditView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.EventDeleteView.as_view(), name="delete"),
    # path("<int:pk>/close/", views.CloseEventView.as_view(), name="close"),
    path(
        "<int:pk>/add_active/",
        views.AddActiveEventView.as_view(),
        name="add_active",
    ),
    path(
        "<int:pk>/remove_active/",
        views.RemoveActiveEventView.as_view(),
        name="remove_active",
    ),
    path("<int:pk>/<slug>/", views.EventView.as_view(), name="detail"),
    path("<int:pk>/<slug>/admin/", views.EventAdminView.as_view(), name="detail_admin"),
    path(
        "<int:pk>/<slug>/book/<int:user_pk>",
        views.EventBookStuffView.as_view(),
        name="book_confirm",
    ),
    path(
        "<int:pk>/add_stuff/<int:user_pk>",
        views.EventAddStuffView.as_view(),
        name="add_stuff_event",
    ),
    path(
        "create_stuff/<int:event_pk>/<int:registered_pk>",
        views.StuffUserEventFormView.as_view(),
        name="create_user_event_stuff",
    ),
    path(
        "create_stuff_orga/<int:event_pk>/<int:registered_pk>",
        views.StuffUserOrgaEventFormView.as_view(),
        name="create_user_event_stuff_orga",
    ),
    path(
        "cancel_reservation/<token>/",
        views.CancelReservationView.as_view(),
        name="cancel_reservation",
    ),
    path("book/<token>/", views.BookView.as_view(), name="book"),
    path("absent/<token>/", views.AbsentView.as_view(), name="user_absent"),
    path("present/<token>/", views.PresentView.as_view(), name="user_present"),
    path(
        "add-to-member/<int:pk>/<int:event_pk>/",
        CreateMembershipMixin.as_view(),
        name="add_member",
    ),
    path(
        "update-member/<int:orga_pk>/<int:pk>/<int:event_pk>/",
        UpdateMembershipMixin.as_view(),
        name="update_member",
    ),
    path(
        "add-participation/<int:user_pk>/<int:event_pk>/",
        views.ParticipationCreateView.as_view(),
        name="add_participation",
    ),
    path(
        "update-participation/<int:pk>/",
        views.ParticipationUpdateView.as_view(),
        name="update_participation",
    ),
    path(
        "delete-participation/<int:pk>/",
        views.ParticipationDeleteView.as_view(),
        name="delete_participation",
    ),
    path(
        "ical-event/<int:pk>/",
        views.EventICSView.as_view(),
        name="ical_event",
    ),
    path(
        "ical-events/<int:pk>/",
        views.EventByOrganizationICSView.as_view(),
        name="ical_events",
    ),
    path(
        "invitation/<token>/",
        views.InvitationFormView.as_view(),
        name="invitation",
    ),
]

openrepairplatform/inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"
urlpatterns = [
    path(
        "device_autocomplete/",
        views.DeviceAutocomplete.as_view(),
        name="device_autocomplete",
    ),
    path(
        "brand_autocomplete/",
        views.BrandAutocomplete.as_view(create_field="name"),
        name="brand_autocomplete",
    ),
    path(
        "action_autocomplete/",
        views.ActionAutocomplete.as_view(create_field="name"),
        name="action_autocomplete",
    ),
    path(
        "observation_autocomplete/",
        views.ObservationAutocomplete.as_view(create_field="name"),
        name="observation_autocomplete",
    ),
    path(
        "status_autocomplete/",
        views.StatusAutocomplete.as_view(create_field="name"),
        name="status_autocomplete",
    ),
    path(
        "reasoning_autocomplete/",
        views.ReasoningAutocomplete.as_view(create_field="name"),
        name="reasoning_autocomplete",
    ),
    path(
        "category_autocomplete/",
        views.CategoryAutocomplete.as_view(),
        name="category_autocomplete",
    ),
    path(
        "device/<int:pk>/<slug>/", views.DeviceDetailView.as_view(), name="device_view"
    ),
    path("", views.StockListView.as_view(), name="stock_list"),
    path("stuff/<int:stuff_pk>/", views.StuffDetailView.as_view(), name="stuff_view"),
    path(
        "user_stuff_list/<int:user_pk>/",
        views.StuffUserListView,
        name="user_stuff_list",
    ),
    path(
        "create_stuff/<int:user_pk>/",
        views.StuffUserFormView.as_view(),
        name="create_user_stuff",
    ),
    path(
        "create_stuff/<str:orga_slug>/",
        views.StuffOrganizationFormView.as_view(),
        name="create_organization_stuff",
    ),
    path(
        "update_stuff/<int:pk>/", views.StuffUpdateView.as_view(), name="update_stuff"
    ),
    path(
        "update_owner_stuff/<int:pk>/",
        views.StuffUpdateOwnerView.as_view(),
        name="update_owner_stuff",
    ),
    path(
        "update_visibility_stuff/<int:pk>/",
        views.StuffEditVisibilityStuffView.as_view(),
        name="update_visibility_stuff",
    ),
    path(
        "update_place_stuff/<int:pk>/",
        views.StuffUpdatePlaceView.as_view(),
        name="update_place_stuff",
    ),
    path(
        "update_state_stuff/<int:pk>/",
        views.StuffUpdateStateView.as_view(),
        name="update_state_stuff",
    ),
    path(
        "create_folder/<int:pk>/",
        views.FolderCreateView.as_view(),
        name="create_folder",
    ),
    path(
        "create_intervention/<int:pk>/",
        views.InterventionCreateView.as_view(),
        name="create_intervention",
    ),
    path(
        "update_intervention/<int:pk>/",
        views.InterventionUpdateView.as_view(),
        name="update_intervention",
    ),

    path(
        "print_thermal_label/<int:pk>/",
        views.print_thermal_label,
        name="print_thermal_label",
    ),

]

openrepairplatform/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

import debug_toolbar

from . import views
from openrepairplatform.inventory.views import OrganizationStockView


urlpatterns = [
    # View test vuejs
    path("", views.HomeView.as_view(), name="homepage"),
    path(
        "mentions-legales/",
        views.MentionsView.as_view(),
        name="mentions-legales",
    ),
    path(
        "a-propos/",
        views.AboutView.as_view(),
        name="a-propos",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("where/", views.LocaliseRedirect.as_view(), name="where"),
    path("user/", include("openrepairplatform.user.urls", namespace="user")),
    path("avatar/", include("initial_avatars.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("event/", include("openrepairplatform.event.urls", namespace="event")),
    path(
        "inventory/",
        include("openrepairplatform.inventory.urls", namespace="inventory"),
    ),
    path(
        "location/",
        include("openrepairplatform.location.urls", namespace="location"),
    ),
    path(
        "api/location/",
        include("openrepairplatform.location.api_urls", namespace="api_location"),
    ),
    
    path(
        "api/user/",
        include("openrepairplatform.user.api_urls", namespace="api_user"),
    ),
    path(
        "api/event/",
        include("openrepairplatform.event.api_urls", namespace="api_event"),
    ),
    path(
        "place_autocomplete/",
        views.PlaceAutocomplete.as_view(),
        name="place_autocomplete",
    ),
    path(
        "activity_autocomplete/",
        views.ActivityAutocomplete.as_view(),
        name="activity_autocomplete",
    ),
    path(
        "user_autocomplete/",
        views.CustomUserAutocomplete.as_view(),
        name="user_autocomplete",
    ),
    path(
        "<str:orga_slug>/user_orga_autocomplete/",
        views.ActiveOrgaAutocomplete.as_view(),
        name="user_orga_autocomplete",
    ),
    path(
        "<str:orga_slug>/",
        views.OrganizationPageView.as_view(),
        name="organization_page",
    ),
    path(
        "<str:orga_slug>/groups/",
        views.OrganizationGroupsView.as_view(),
        name="organization_groups",
    ),
    path(
        "<str:orga_slug>/members/",
        views.OrganizationMembersView.as_view(),
        name="organization_members",
    ),
    path(
        "<str:orga_slug>/details/",
        views.OrganizationDetailsView.as_view(),
        name="organization_details",
    ),
    path(
        "<str:orga_slug>/controls/",
        views.OrganizationControlsView.as_view(),
        name="organization_controls",
    ),
    path(
        "<str:orga_slug>/events/",
        views.OrganizationEventsView.as_view(),
        name="organization_events",
    ),
    path(
        "<str:orga_slug>/stock/",
        OrganizationStockView.as_view(),
        name="organization_stock",
    ),
    path(
        "<str:orga_slug>/accounting/",
        views.OrganizationFeesView.as_view(),
        name="organization_fees",
    ),
    
    path(r"tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))] 

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openrepairplatform/user/urls.py
from django.urls import path

from . import views
from openrepairplatform.mixins import (
    CreateMembershipMixin,
    UpdateMembershipMixin,
    DeleteMembershipMixin,
)

app_name = "user"
urlpatterns = [
    path("<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("update/<int:pk>", views.UserUpdateView.as_view(), name="user_update"),
    path("create/", views.UserCreateView.as_view(), name="user_create"),
    path(
        "create_and_book/",
        views.UserCreateAndBookView.as_view(),
        name="create_and_book",
    ),
    path(
        "organizer_book/<int:pk>/",
        views.OrganizerBookView.as_view(),
        name="organizer_book",
    ),
    path(
        "organizations/",
        views.OrganizationListView.as_view(),
        name="organization_list",
    ),
    path(
        "organization/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "organization/<int:pk>/update/",
        views.OrganizationUpdateView.as_view(),
        name="organization_update",
    ),
    path(
        "organization/<int:orga_pk>/<slug>/events/<int:page>/",
        views.OrganizationEventsListView.as_view(),
        name="organization_all_events",
    ),
    path(
        "organization/<int:pk>/",
        views.OrganizationDeleteView.as_view(),
        name="organization_delete",
    ),
    path(
        "organization/<int:pk>/add-admin",
        views.AddAdminToOrganization.as_view(),
        name="organization_add_admin",
    ),
    path(
        "organization/<int:pk>/add-active",
        views.AddActiveToOrganization.as_view(),
        name="organization_add_active",
    ),
    path(
        "organization/<int:pk>/add-volunteer",
        views.AddVolunteerToOrganization.as_view(),
        name="organization_add_volunteer",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-actives",
        views.RemoveActiveFromOrganization.as_view(),
        name="remove_from_actives",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-volunteers",
        views.RemoveVolunteerFromOrganization.as_view(),
        name="remove_from_volunteers",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-admins",
        views.RemoveAdminFromOrganization.as_view(),
        name="remove_from_admins",
    ),
    path(
        "organization/<int:pk>/add-member",
        CreateMembershipMixin.as_view(),
        name="organization_add_member",
    ),
    path(
        "organization/<int:orga_pk>/update-member/<int:pk>",
        UpdateMembershipMixin.as_view(),
        name="organization_update_member",
    ),
    path(
        "delete-member/<int:pk>", DeleteMembershipMixin.as_view(), name="delete_member"
    ),
    path(
        "fee/<int:pk>/delete/",
        views.FeeDeleteView.as_view(),
        name="fee_delete",
    ),
    path(
        "fee/create/",
        views.FeeCreateView.as_view(),
        name="fee_create",
    )
]

openrepairplatform/user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from datetime import date as dt
from dal import autocomplete

from .models import CustomUser, Organization, Fee, Membership


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["email"]


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = CustomUser


class UserCreateForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["email", "first_name", "last_name", "street_address"]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            "email",
            "first_name",
            "last_name",
            "avatar_img",
            "phone_number",
            "street_address",
            "birth_date",
            "gender",
            "bio",
            "is_visible",
        ]
        widgets = {
            "birth_date": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d")
        }


class CustomUserEmailForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email"]


class CustomUserSearchForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=CustomUser.objects.all(),
        label="Veuillez rechercher si l'utilisateur existe avant de le créer",
        widget=autocomplete.ModelSelect2(
            url="user_autocomplete",
            attrs={"data-html": True, "data-allow-clear": "true"},
        ),
    )


class MoreInfoCustomUserForm(forms.ModelForm):
    amount_paid = forms.IntegerField(min_value=0, initial=0)
    payment = forms.ChoiceField(
        choices=[
            (1, "Espèces"),
            (2, "Online"),
            (3, "Chèque"),
            (4, "CB"),
            (5, "Monnaie locale"),
        ],
        label="Type de paiement",
    )
    date = forms.DateField(initial=dt.today)

    class Meta:
        model = CustomUser
        fields = ["email", "first_name", "last_name", "street_address"]


class OrganizationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["picture"].widget.attrs.update({"class": "form-control"})
        self.fields["fee_description"].widget = forms.TextInput()

    class Meta:
        model = Organization
        exclude = [
            "visitors",
            "members",
            "actives",
            "volunteers",
            "admins",
            "slug",
        ]


class AddFeeForm(forms.ModelForm):
    membership = forms.ModelChoiceField(
        queryset=Membership.objects.all(), widget=forms.HiddenInput()
    )
    organization = forms.ModelChoiceField(
        queryset=Organization.objects.all(), widget=forms.HiddenInput()
    )

    class Meta:
        model = Fee
        fields = [
            "payment",
            "date",
            "amount",
            "membership",
            "organization",
        ]

openrepairplatform/user/templates/user/profile/account.html
{% load assets app_filters thumbnail bootstrap5 %}
<h4 class="mt-4">Etat des adhésions</h4>
{% for membership in object.memberships.all %}
    {% if membership.organization in user.admin_organizations.all or user.volunteer_organizations.all or user.active_organizations.all or object == user %}
        <div class="card p-2">
            <h5 class="pb-2">
                {{ membership.organization }}
                <small>depuis le {{ membership.first_payment|date:"d F Y" }}</small>
                {% if membership.current_contribution == 0 %}
                    <small class="text-danger">Pas à jour</small>
                {% elif membership.current_contribution >= membership.organization.advised_fee %}
                    <small class="text-success">A jour</small>
                {% else %}
                    <small class="text-warning">Incomplet</small>
                {% endif %}
                <span class="badge badge-pill badge-success float-right">{{ membership.current_contribution }}€</span>
            </h5>
            {% if can_create and not same_user %}
                <div class="m-2">
                    <label class="btn btn-primary"
                        for="modal_fee_{{ membership.organization.name }}">Ajouter une cotisation</label>
                    <input class="toggle-modal"
                        id="modal_fee_{{ membership.organization.name }}"
                        type="checkbox">
                    <section class="modal fade" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Ajout d'une cotisation</h5>
                                    <label class="close" for="modal_fee_{{ membership.organization.name }}">×</label>
                                </div>
                                <div class="modal-body">
                                    <form method="post" action="{% url 'user:fee_create' %}">
                                        {% csrf_token %}
                                        {% for field in add_fee_form %}
                                            {% if field.name == 'organization' %}
                                                <input type="hidden"
                                                    name="{{ field.name }}"
                                                    value="{{ membership.organization.pk|escape }}" />
                                            {% elif field.name == 'membership' %}
                                                <input type="hidden"
                                                    name="{{ field.name }}"
                                                    value="{{ membership.pk|escape }}" />
                                            {% else %}
                                                {% bootstrap_field field %}
                                            {% endif %}
                                        {% endfor %}
                                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            {% endif %}
            <table class="table table-striped table-hover">
                {% for fee in membership.fees.all %}
                    <tr>
                        <td>
                            le {{ fee.date|date:"d F Y" }}
                            {% if fee.membership and fee.date == membership.first_payment %}
                                <span class="badge badge-pill bg-warning">référence</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if fee.participation %}
                            <a href="{% url 'event:detail' fee.participation.event.pk fee.participation.event.slug %}">{{ fee.participation.event }}</a>
                        {% else %}
                            Cotisation manuelle
                        {% endif %}
                    </td>
                    <td class="text-right">
                        <b>{{ fee.amount }}€</b>
                        <br>
                        <small>{{ fee.get_payment_display }}</small>
                    </td>
                    <td>
                        {% if membership.organization in user.admin_organizations.all or user.volunteer_organizations.all or user.active_organizations.all %}
                            <form action="{% url 'user:fee_delete' fee.pk %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="fa fa-trash-alt"></i>
                                </button>
                            </form>
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
    <div class="card p-2 text-warning">
        Vous ne pouvez pas visualiser les cotisations concernant une organisation dont vous n'êtes membre
    </div>
{% endif %}
{% empty %}
    <div class="card p-2 m-2 text-warning">Cet utilisateur n'a pas de cotisation en cours</div>
{% endfor %}

openrepairplatform/user/templates/user/profile/inventory.html
{% load assets static app_filters thumbnail bootstrap5 %}
<h4 class="mt-4">{{ stock.all.count }} Objets inventoriés</h4>
<div class="card p-2 pt-2">
    {% if can_create %}
        <div class=m-2>
            <button type="button"
                class="btn btn-primary bs-gobal-modal"
                data-form-url="{% url 'inventory:create_user_stuff' object.pk %}">Ajouter un objet à l'inventaire</button>
        </div>
    {% endif %}
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Objet</th>
                    <th>Localisation</th>
                    <th>Etat</th>
                </tr>
            </thead>
            <tbody>
                {% for stuff in stock %}
                    <tr>
                        <td scope="row">
                            <a href="{{ stuff.get_absolute_url }}">{{ stuff }}</a>
                        </td>
                        <td>
                            {% if stuff.place %}
                                <a href="{% url 'location:detail' stuff.place.id stuff.place.slug %}">{{ stuff.place.name }}</a>
                            {% else %}
                                Chez l'utilisateur
                            {% endif %}
                        </td>
                        <td>{% include "inventory/stuff_state_display.html" with stuff_state=stuff.get_state_display %}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">Cet utilisateur n'a pas d'objet dans son inventaire</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% block extra_js %}
    {% assets "js_create_stuff" %}
        <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock extra_js %}

openrepairplatform/user/templates/user/profile/rdv.html
{% load assets app_filters thumbnail bootstrap5 %}
<h4 class="mt-4">Rendez-vous</h4>
{% if passed_rendezvous or future_rendezvous %}
  {% if future_rendezvous %}
    <div class="card p-2">
      <h4 class="mt-4 text-left">A venir</h4>
      <div class="table-responsive">
        <table class="table">
          <tbody>
            {% for event, status in future_rendezvous reversed %}
              {% ifchanged %}
                <tr>
                  <td colspan="4" class="bg-light">
                    <b>{{ event.date|date:"F" }} {{ event.date|date:"Y" }}</b>
                  </td>
                </tr>
              {% endifchanged %}
              <tr class="{% if event.date <= today %}bg-light text-muted{% else %}bg-white{% endif %}">
                <td>{% include "extra_column_data.html" with column="date" record=event %}</td>
                <td>
                  <a href="{% url 'event:detail' event.pk event.slug %}">
                    <b>
                      {% if event.activity %}
                        {{ event.activity }}
                      {% else %}
                        Type d'activité supprimé
                      {% endif %}
                    </b>
                  </a>
                </td>
                <td>
                  <small>{{ event.location }}</small>
                  </td>
                  <td>
                    {% if status == "organizer" %}
                      <span class="badge badge-pill bg-success">Animateur</span>
                    {% else %}
                      {% if object.pk == request.user.pk %}
                        {% tokenize user=object event=event action='cancel' as tok %}
                        <button class="btn btn-sm btn-danger">
                          <a href="{% url 'event:cancel_reservation' tok %}">
                            <i class="fa fa-times"></i>
                          </a>
                        </button>
                      {% endif %}
                    {% endif %}
                  </td>
                </tr>
              {% empty %}
                Pas d'évènements
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    {% endif %}
    {% if passed_rendezvous %}
      <div class="card p-2">
        <h4 class="mt-4 text-left">Passés</h4>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              {% for event, status in passed_rendezvous %}
                {% ifchanged %}
                  <tr>
                    <td colspan="4" class="bg-light">
                      <b>{{ event.date|date:"F" }} {{ event.date|date:"Y" }}</b>
                    </td>
                  </tr>
                {% endifchanged %}
                <tr class="bg-light text-muted">
                  <td>{% include "extra_column_data.html" with column="date" record=event %}</td>
                  <td>
                    <a href="{% url 'event:detail' event.pk event.slug %}">
                      <b>
                        {% if event.activity %}
                          {{ event.activity }}
                        {% else %}
                          Type d'activité supprimé
                        {% endif %}
                      </b>
                    </a>
                  </td>
                  <td>
                    <small>{{ event.location }}</small>
                  </td>
                  <td>
                    {% if status == "organizer" %}
                      <span class="badge badge-pill bg-success">Animateur</span>
                    {% elif status == "absent" %}
                      <span class="badge badge-pill bg-secondary">Absent</span>
                    {% elif status == "present" %}
                      <span class="badge badge-pill bg-info">A participé</span>
                    {% endif %}
                  </td>
                </tr>
              {% empty %}
                Pas d'évènements
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      {% endif %}
    {% else %}
      Cet utilisateur n'a pas de réservations
    {% endif %}