openrepairplatform/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

import debug_toolbar

from . import views
from openrepairplatform.inventory.views import OrganizationStockView


urlpatterns = [
    # View test vuejs
    path("", views.HomeView.as_view(), name="homepage"),
    path(
        "mentions-legales/",
        views.MentionsView.as_view(),
        name="mentions-legales",
    ),
    path(
        "a-propos/",
        views.AboutView.as_view(),
        name="a-propos",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("where/", views.LocaliseRedirect.as_view(), name="where"),
    path("user/", include("openrepairplatform.user.urls", namespace="user")),
    path("avatar/", include("initial_avatars.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("event/", include("openrepairplatform.event.urls", namespace="event")),
    path(
        "inventory/",
        include("openrepairplatform.inventory.urls", namespace="inventory"),
    ),
    path(
        "location/",
        include("openrepairplatform.location.urls", namespace="location"),
    ),
    path(
        "api/location/",
        include("openrepairplatform.location.api_urls", namespace="api_location"),
    ),
    
    path(
        "api/user/",
        include("openrepairplatform.user.api_urls", namespace="api_user"),
    ),
    path(
        "api/event/",
        include("openrepairplatform.event.api_urls", namespace="api_event"),
    ),
    path(
        "place_autocomplete/",
        views.PlaceAutocomplete.as_view(),
        name="place_autocomplete",
    ),
    path(
        "activity_autocomplete/",
        views.ActivityAutocomplete.as_view(),
        name="activity_autocomplete",
    ),
    path(
        "user_autocomplete/",
        views.CustomUserAutocomplete.as_view(),
        name="user_autocomplete",
    ),
    path(
        "<str:orga_slug>/user_orga_autocomplete/",
        views.ActiveOrgaAutocomplete.as_view(),
        name="user_orga_autocomplete",
    ),
    path(
        "<str:orga_slug>/",
        views.OrganizationPageView.as_view(),
        name="organization_page",
    ),
    path(
        "<str:orga_slug>/groups/",
        views.OrganizationGroupsView.as_view(),
        name="organization_groups",
    ),
    path(
        "<str:orga_slug>/members/",
        views.OrganizationMembersView.as_view(),
        name="organization_members",
    ),
    path(
        "<str:orga_slug>/details/",
        views.OrganizationDetailsView.as_view(),
        name="organization_details",
    ),
    path(
        "<str:orga_slug>/controls/",
        views.OrganizationControlsView.as_view(),
        name="organization_controls",
    ),
    path(
        "<str:orga_slug>/events/",
        views.OrganizationEventsView.as_view(),
        name="organization_events",
    ),
    path(
        "<str:orga_slug>/stock/",
        OrganizationStockView.as_view(),
        name="organization_stock",
    ),
    path(
        "<str:orga_slug>/accounting/",
        views.OrganizationFeesView.as_view(),
        name="organization_fees",
    ),
    
    path(r"tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))] 

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openrepairplatform/user/urls.py
from django.urls import path

from . import views
from openrepairplatform.mixins import (
    CreateMembershipMixin,
    UpdateMembershipMixin,
    DeleteMembershipMixin,
)

app_name = "user"
urlpatterns = [
    path("<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("update/<int:pk>", views.UserUpdateView.as_view(), name="user_update"),
    path("create/", views.UserCreateView.as_view(), name="user_create"),
    path(
        "create_and_book/",
        views.UserCreateAndBookView.as_view(),
        name="create_and_book",
    ),
    path(
        "organizer_book/<int:pk>/",
        views.OrganizerBookView.as_view(),
        name="organizer_book",
    ),
    path(
        "organizations/",
        views.OrganizationListView.as_view(),
        name="organization_list",
    ),
    path(
        "organization/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "organization/<int:pk>/update/",
        views.OrganizationUpdateView.as_view(),
        name="organization_update",
    ),
    path(
        "organization/<int:orga_pk>/<slug>/events/<int:page>/",
        views.OrganizationEventsListView.as_view(),
        name="organization_all_events",
    ),
    path(
        "organization/<int:pk>/",
        views.OrganizationDeleteView.as_view(),
        name="organization_delete",
    ),
    path(
        "organization/<int:pk>/add-admin",
        views.AddAdminToOrganization.as_view(),
        name="organization_add_admin",
    ),
    path(
        "organization/<int:pk>/add-active",
        views.AddActiveToOrganization.as_view(),
        name="organization_add_active",
    ),
    path(
        "organization/<int:pk>/add-volunteer",
        views.AddVolunteerToOrganization.as_view(),
        name="organization_add_volunteer",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-actives",
        views.RemoveActiveFromOrganization.as_view(),
        name="remove_from_actives",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-volunteers",
        views.RemoveVolunteerFromOrganization.as_view(),
        name="remove_from_volunteers",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-admins",
        views.RemoveAdminFromOrganization.as_view(),
        name="remove_from_admins",
    ),
    path(
        "organization/<int:pk>/add-member",
        CreateMembershipMixin.as_view(),
        name="organization_add_member",
    ),
    path(
        "organization/<int:orga_pk>/update-member/<int:pk>",
        UpdateMembershipMixin.as_view(),
        name="organization_update_member",
    ),
    path(
        "delete-member/<int:pk>", DeleteMembershipMixin.as_view(), name="delete_member"
    ),
    path(
        "fee/<int:pk>/delete/",
        views.FeeDeleteView.as_view(),
        name="fee_delete",
    ),
    path(
        "fee/create/",
        views.FeeCreateView.as_view(),
        name="fee_create",
    )
]

openrepairplatform/user/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
    RedirectView,
)
from openrepairplatform.event.models import Event, Participation
from openrepairplatform.location.models import Place
from openrepairplatform.event.templatetags.app_filters import tokenize
from openrepairplatform.mixins import (
    HasAdminPermissionMixin,
    HasActivePermissionMixin,
    HasVolunteerPermissionMixin,
    LocationOrganization,
)
from openrepairplatform.inventory.mixins import PermissionCreateUserStuffMixin
from openrepairplatform.user.models import CustomUser, Organization, Fee
from openrepairplatform.inventory.models import Stuff
from openrepairplatform.inventory.forms import StuffForm

from .forms import (
    UserUpdateForm,
    UserCreateForm,
    OrganizationForm,
    CustomUserEmailForm,
    AddFeeForm,
)

EVENTS_PER_PAGE = 6


class UserUpdateView(UserPassesTestMixin, UpdateView):
    model = CustomUser
    template_name = "user/user_form.html"
    form_class = UserUpdateForm

    def form_valid(self, form):
        res = super().form_valid(form)
        messages.success(self.request, "L'utilisateur a bien été mis à jour.")
        return res

    def test_func(self):
        return self.request.user == self.get_object()


class UserCreateView(CreateView):
    model = CustomUser
    template_name = "user/user_form.html"
    form_class = UserCreateForm
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        res = super().form_valid(form)
        messages.success(self.request, "L'utilisateur a bien été créé")
        return res


class UserCreateAndBookView(CreateView):
    model = CustomUser
    form_class = CustomUserEmailForm
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        self.object = CustomUser.objects.filter(
            email=self.request.POST.get("email", "invalid email")
        ).first()
        if self.object:
            event = Event.objects.get(id=self.request.GET.get("event"))
            organizers = event.organizers.all()
            if self.object in organizers:
                messages.error(
                    self.request, "Vous existez déjà comme animateur de cet événement"
                )
                return redirect(
                    reverse(
                        "event:detail",
                        kwargs={
                            "pk": request.GET["event"],
                            "slug": event.slug,
                        },
                    )
                )
            return redirect(self.get_success_url())
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        event_id = self.request.GET.get("event")
        redirect_url = self.request.GET.get("redirect")
        event = get_object_or_404(Event, pk=event_id)
        token = tokenize(self.object, event, "book")
        return (
            reverse("event:book", kwargs={"token": token}) + f"?redirect={redirect_url}"
        )


class OrganizerBookView(HasVolunteerPermissionMixin, RedirectView):
    model = Event
    form_class = CustomUserEmailForm
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        new_organizer = CustomUser.objects.filter(
            email=self.request.POST.get("email", "invalid email")
        ).first()
        event = self.model.objects.get(id=kwargs["pk"])
        if new_organizer and new_organizer in (
            self.organization.actives_or_more.all()
            .union(self.organization.volunteers.all())
            .difference(event.registered.all())
        ):
            if new_organizer in event.organizers.all():
                messages.error(
                    request,
                    str(new_organizer) + " est déjà animateur.trice de cet événement",
                )
            else:
                messages.success(
                    request,
                    str(new_organizer)
                    + " rajouté.e comme animateur.trice de cet événement",
                )
            event.organizers.add(new_organizer)
            event.save()
            return redirect(event.get_absolute_url() + "admin/")
        messages.error(self.request, "Impossible de rajouter cette personne")
        return redirect(event.get_absolute_url())


class UserDetailView(PermissionCreateUserStuffMixin, DetailView):
    model = CustomUser
    template_name = "user/user_detail.html"

    def get_object(self, queryset=None):
        custom_user = super().get_object(queryset=queryset)
        user = self.request.user

        if custom_user.is_visible:
            return custom_user

        if user.is_staff:
            return custom_user

        if user.is_authenticated:
            if user.pk == custom_user.pk:
                return custom_user

            organizations = user.active_organizations.all().union(
                user.volunteer_organizations.all(),
                user.admin_organizations.all(),
            )
            can_see_users = CustomUser.objects.filter(
                Q(registered_events__organization__in=list(organizations))
                | Q(presents_events__organization__in=list(organizations))
            )

            for organization in organizations.all():
                if organization in custom_user.member_organizations.all():
                    return custom_user

            if custom_user in can_see_users:
                return custom_user

        raise Http404("Utilisateur introuvable")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = context["object"]
        registered = list(user.registered_events.all())
        participations = list(Participation.objects.filter(user=user))
        context["passed_participations"] = [
            (participation.event, participation.amount)
            for participation in participations
        ]
        context["passed_rendezvous"] = (
            [(event, "present") for event in user.presents_events.all()]
            + [(event, "absent") for event in registered if event.has_ended and event not in user.presents_events.all()]
            + [
                (event, "organizer")
                for event in user.organizers_events.all()
                if event.has_ended
            ]
        )
        context["future_rendezvous"] = [
            (event, "") for event in registered if not event.has_ended
        ] + [
            (event, "organizer")
            for event in user.organizers_events.all()
            if not event.has_ended
        ]
        context["passed_rendezvous"].sort(key=lambda evt: evt[0].date, reverse=True)
        context["future_rendezvous"].sort(key=lambda evt: evt[0].date)
        context["stock"] = Stuff.objects.filter(member_owner=self.get_object())
        context["add_member_stuff"] = StuffForm
        context["add_fee_form"] = AddFeeForm
        return context


class UserListView(ListView):
    model = CustomUser
    context_object_name = "users"
    template_name = "user/user_list.html"
    paginate_by = 9
    queryset = CustomUser.objects.filter(is_superuser=False, is_visible=True).order_by(
        "last_name"
    )


class OrganizationEventsListView(HasVolunteerPermissionMixin, ListView):
    model = Event
    paginate_by = EVENTS_PER_PAGE
    template_name = "user/organization/organization_event_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        organization = Organization.objects.get(pk=self.kwargs.get("orga_pk"))
        context["organization"] = organization
        return context

    def get_queryset(self):
        orga_pk = self.kwargs.get("orga_pk")
        organization = get_object_or_404(Organization, pk=orga_pk)
        return organization.events.order_by("date")


class OrganizationListView(LocationOrganization, ListView):
    model = Organization
    template_name = "user/organization/organization_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["organization_menu"] = "active"
        return context

    def get_queryset(self):
        queryset = self.filter_queryset_location(super().get_queryset())
        return queryset

    def get(self, request, *args, **kwargs):
        res = super().get(request, *args, **kwargs)

        places = Place.objects.all()
        if not self.get_queryset().exists():
            zipcodes = "<br/>".join({
                f"- {place.zipcode}" for place in places if place.address
            })
            message = f"""
                <p>
                    <b>
                    Il n'y a pas d'organisation dans la zone selectionnée.
                    Vous pouvez retrouver nos organisations de réparation dans les zones
                    suivantes :
                    </b>
                </p>
                {zipcodes}
            """
            messages.info(request, message, extra_tags="safe")

            return HttpResponseRedirect(reverse("homepage"))
        return res


@method_decorator(staff_member_required, name="dispatch")
class OrganizationCreateView(CreateView):
    template_name = "user/organization/organization_form.html"
    model = Organization
    form_class = OrganizationForm

    def form_valid(self, form):
        res = super().form_valid(form)
        form.instance.admins.add(self.request.user)
        messages.success(self.request, "L'organisation a bien été créée")
        return res

openrepairplatform/user/templates/user/membership_pill.html
{% load assets l10n app_filters %}

{% if membership %}
  {% with org=membership.organization %}
    {% if membership.current_contribution == 0 and org.advised_fee > 0 %}
      <span class="text-danger">Pas de cotisation</span>
      <span class="badge badge-pill bg-danger">0€</span>

    {% elif membership.current_contribution == 0 and org.advised_fee == 0 and org.min_fee == 0 %}
      <span class="text-success">A jour</span>
      <span class="badge badge-pill bg-success">
        {{ membership.current_contribution }}€/{{ org.advised_fee }}€
      </span>

    {% elif membership.current_contribution >= org.advised_fee %}
      <span class="text-success">A jour</span>
      <span class="badge badge-pill bg-success">
        {{ membership.current_contribution }}€/{{ org.advised_fee }}€
      </span>

    {% else %}
      <span class="text-warning">Incomplet</span>
      <span class="badge badge-pill bg-warning">
        {{ membership.current_contribution }}€/{{ org.advised_fee }}€
      </span>
    {% endif %}
  {% endwith %}
{% else %}
  <span class="badge badge-pill bg-warning">Non membre</span>
{% endif %}

openrepairplatform/user/templates/user/user_card.html
{% load thumbnail %}
{% load assets l10n app_filters %}
{% load initialavatar %}

{% for user in users %}
<div class="col">
  <div class="card p-2">
    <a class="card-link" href="{{ user.get_absolute_url }}">
      <div class="row">
      {% if event_control == True %}
        {% filter_orga queryset=user.memberships organization=event.organization as membership %}
        {% if membership %}
          {% if membership.current_contribution == 0 %}
            <span class="badge badge-pill bg-primary text-danger float-start" >0€</span>
          {% elif membership.current_contribution >= event.organization.advised_fee %}
            <span class="badge badge-pill bg-primary text-success float-start">{{ membership.current_contribution }}€</span>
          {% else %}
            <span class="badge badge-pill bg-primary text-warning float-start" >{{ membership.current_contribution }}€</span>
          {% endif %}
        {% else %}
          <span class="badge badge-pill bg-primary text-danger float-start" >0€</span>
        {% endif %}
      {% endif %}
      </div>
      <div class="row" id="square-{{ user.pk }}">
        <div class="col-2 mb-1">
          {% if user.avatar_img %}
            {% thumbnail user.avatar_img "50x50" crop="center" format="PNG" as im %}
              <img src="{{ im.url }}" class="m-2 rounded-circle"/>
            {% endthumbnail %}
          {% else %}
            {% if user.first_name %}
              {% get_initial_avatar user 50 'circle' %}
            {% endif %}
          {% endif %}
        </div>
        <div class="col-8 text-left">
          <h5 style="line-height: 45px !important;">
              {{ user}}
          </h5>
        </div>
        {% if event_control == True %}
          {% if event.has_started and is_active %}
            {% include "event/modal_more_info.html" with user=user form=present_form|initial:user %}
          {% endif %}
        {% endif %}
      
        {% if admin_remove_controls == True %}
          {% if is_admin %}
            <form action="{% url 'user:remove_from_admins' organization.pk user.pk %}" class="col-2">
              {% csrf_token %}
              <button type="submit" class="btn badge badge-pill bg-danger float-end" onclick="return confirm('Êtes-vous sûr ?')">&times;</button>
            </form>
          {% endif %}
        {% endif %}

        {% if active_remove_controls == True %}
          {% if is_admin %}
          <form action="{% url 'user:remove_from_actives' organization.pk user.pk %}" class="col-2">
            {% csrf_token %}
            <button type="submit" class="btn badge badge-pill bg-danger float-end" onclick="return confirm('Êtes-vous sûr ?')">&times;</button>
          </form>
          {% endif %}
        {% endif %}

        {% if volunteer_remove_controls == True %}
          {% if is_admin %}
          <form action="{% url 'user:remove_from_volunteers' organization.pk user.pk %}" class="col-2">
            {% csrf_token %}
            <button type="submit" class="btn badge badge-pill bg-danger float-end" onclick="return confirm('Êtes-vous sûr ?')">&times;</button>
          </form>
          {% endif %}
        {% endif %}
      </div>
    </a>
  </div>
</div>
{% empty %}
  <div class="col-lg">Pas encore d'utilisateur</div>
{% endfor %}

openrepairplatform/user/templates/user/user_detail.html
{% extends "base.html" %}
{% load static assets app_filters thumbnail initialavatar bootstrap5 %}
{% block title %}
  Profil de {{ object }} sur {{ site_title }}
{% endblock title %}
{% block content %}
  <!-- modals -->
  <div class="modal fade" tabindex="-1" data-bs-focus="false" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
  {% if request.user.pk == object.pk and not object.first_name or not object.last_name or not object.street_address %}
    <div class="alert alert-warning" role="alert">
      Pour devenir membre d'une organisation, vous devez renseigner votre Nom, Prénom
      et Adresse postale.
    </div>
  {% endif %}
  {% include "breadcrumb.html" with current=object first_parent_url=user_detail_url first_parent_text="Communauté" %}
  <div class="jumbotron jumbotron-fluid no-padding-jumbotron" id="jumbotron">
    <div class="text-center d-flex justify-content-center align-items-center flex-md-column">
      <div class="header_detail_page_picture">
        <div class="mt-2 header_detail_page_picture rounded">
          {% if object.avatar_img %}
            {% thumbnail object.avatar_img "150x150" crop="center" format="PNG" as im %}
            <img src="{{ im.url }}"
                 width="150"
                 height="150"
                 alt="{{ object }}"
                 class="m-2 rounded-circle" />
          {% endthumbnail %}
        {% else %}
          {% if object.first_name %}
            {% get_initial_avatar object 150 'circle' %}
          {% endif %}
        {% endif %}
      </div>
    </div>
    <h2 class="header_detail_page_title">{{ object }}</h2>
    {% if object.pk == request.user.pk %}
      <a class="btn ms-2 btn-success btn rounded-circle"
         href="{% url "user:user_update" object.pk %}">
        <i class="fa fa-pencil-alt"></i>
      </a>
    {% endif %}
  </div>
  <div class="text-center d-flex justify-content-center align-items-center flex-md-column"
       id="v-pills-tab"
       role="tablist"
       aria-orientation="horizontal">
    <nav class="mt-2">
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active"
                id="nav-home-tab"
                data-bs-toggle="tab"
                data-bs-target="#nav-home"
                type="button"
                role="tab"
                aria-controls="nav-home"
                aria-selected="true">Informations</button>
        <button class="nav-link"
                id="nav-profile-tab"
                data-bs-toggle="tab"
                data-bs-target="#nav-profile"
                href="#nav-profile"
                type="button"
                role="tab"
                aria-controls="nav-profile"
                aria-selected="false">
          Rendez-vous  <span class="badge bg-light">{{ future_rendezvous|length }}</span>
        </button>
        <button class="nav-link"
                id="nav-contact-tab"
                data-bs-toggle="tab"
                data-bs-target="#nav-contact"
                type="button"
                role="tab"
                aria-controls="nav-contact"
                aria-selected="false">Adhésions</button>
        <button class="nav-link"
                id="nav-inventaire-tab"
                data-bs-toggle="tab"
                data-bs-target="#nav-inventaire"
                type="button"
                role="tab"
                aria-controls="nav-inventaire"
                aria-selected="false">Inventaire</button>
      </div>
    </nav>
  </div>
</div>
<div class="container mb-5 mt-5">
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active"
         id="nav-home"
         role="tabpanel"
         aria-labelledby="nav-home-tab"
         tabindex="0">{% include "user/profile/info.html" %}</div>
    <div class="tab-pane fade"
         id="nav-profile"
         role="tabpanel"
         aria-labelledby="nav-profile-tab"
         tabindex="0">{% include "user/profile/rdv.html" %}</div>
    <div class="tab-pane fade"
         id="nav-contact"
         role="tabpanel"
         aria-labelledby="nav-contact-tab"
         tabindex="0">{% include "user/profile/account.html" %}</div>
    <div class="tab-pane fade"
         id="nav-inventaire"
         role="tabpanel"
         aria-labelledby="nav-inventaire-tab"
         tabindex="0">{% include "user/profile/inventory.html" %}</div>
  </div>
</div>
{% endblock content %}

openrepairplatform/user/templates/user/user_form.html
{% extends 'base.html' %}
{% load bootstrap5 assets static %}
{% block title %}
{% if object %}
  Mise à jour du profil de {{user}}
{% else %}
  Créer un profil sur Reparon
{% endif %}
{% endblock %}

{% block content %}
  {% if object %}
    {% include "breadcrumb.html" with current="Mise à jour" second_parent_url=user_detail_url second_parent_text="Communauté" first_parent_url=user_detail_url first_parent_text=object %}
  {% else %}
    {% include "breadcrumb.html" with current="Création" first_parent_text="Communauté" %}
  {% endif %}
<div class="container bg-white">
  <div class="row justify-content-md-center">
    <div class="card p-3 mt-4">
        <h1 class="text-center col-lg bg-white">Créer un compte</h1>
      <form method="post" enctype="multipart/form-data">
        <fieldset>
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-success btn-block">Enregistrer</button>
        </fieldset>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
  {{ form.media }}
  {% assets "js_create_edit_user" %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
{% endblock %}