openrepairplatform/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

import debug_toolbar

from . import views
from openrepairplatform.inventory.views import OrganizationStockView


urlpatterns = [
    # View test vuejs
    path("", views.HomeView.as_view(), name="homepage"),
    path(
        "mentions-legales/",
        views.MentionsView.as_view(),
        name="mentions-legales",
    ),
    path(
        "a-propos/",
        views.AboutView.as_view(),
        name="a-propos",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("where/", views.LocaliseRedirect.as_view(), name="where"),
    path("user/", include("openrepairplatform.user.urls", namespace="user")),
    path("avatar/", include("initial_avatars.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("event/", include("openrepairplatform.event.urls", namespace="event")),
    path(
        "inventory/",
        include("openrepairplatform.inventory.urls", namespace="inventory"),
    ),
    path(
        "location/",
        include("openrepairplatform.location.urls", namespace="location"),
    ),
    path(
        "api/location/",
        include("openrepairplatform.location.api_urls", namespace="api_location"),
    ),
    
    path(
        "api/user/",
        include("openrepairplatform.user.api_urls", namespace="api_user"),
    ),
    path(
        "api/event/",
        include("openrepairplatform.event.api_urls", namespace="api_event"),
    ),
    path(
        "place_autocomplete/",
        views.PlaceAutocomplete.as_view(),
        name="place_autocomplete",
    ),
    path(
        "activity_autocomplete/",
        views.ActivityAutocomplete.as_view(),
        name="activity_autocomplete",
    ),
    path(
        "user_autocomplete/",
        views.CustomUserAutocomplete.as_view(),
        name="user_autocomplete",
    ),
    path(
        "<str:orga_slug>/user_orga_autocomplete/",
        views.ActiveOrgaAutocomplete.as_view(),
        name="user_orga_autocomplete",
    ),
    path(
        "<str:orga_slug>/",
        views.OrganizationPageView.as_view(),
        name="organization_page",
    ),
    path(
        "<str:orga_slug>/groups/",
        views.OrganizationGroupsView.as_view(),
        name="organization_groups",
    ),
    path(
        "<str:orga_slug>/members/",
        views.OrganizationMembersView.as_view(),
        name="organization_members",
    ),
    path(
        "<str:orga_slug>/details/",
        views.OrganizationDetailsView.as_view(),
        name="organization_details",
    ),
    path(
        "<str:orga_slug>/controls/",
        views.OrganizationControlsView.as_view(),
        name="organization_controls",
    ),
    path(
        "<str:orga_slug>/events/",
        views.OrganizationEventsView.as_view(),
        name="organization_events",
    ),
    path(
        "<str:orga_slug>/stock/",
        OrganizationStockView.as_view(),
        name="organization_stock",
    ),
    path(
        "<str:orga_slug>/accounting/",
        views.OrganizationFeesView.as_view(),
        name="organization_fees",
    ),
    
    path(r"tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))] 

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openrepairplatform/user/urls.py
from django.urls import path

from . import views
from openrepairplatform.mixins import (
    CreateMembershipMixin,
    UpdateMembershipMixin,
    DeleteMembershipMixin,
)

app_name = "user"
urlpatterns = [
    path("<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("update/<int:pk>", views.UserUpdateView.as_view(), name="user_update"),
    path("create/", views.UserCreateView.as_view(), name="user_create"),
    path(
        "create_and_book/",
        views.UserCreateAndBookView.as_view(),
        name="create_and_book",
    ),
    path(
        "organizer_book/<int:pk>/",
        views.OrganizerBookView.as_view(),
        name="organizer_book",
    ),
    path(
        "organizations/",
        views.OrganizationListView.as_view(),
        name="organization_list",
    ),
    path(
        "organization/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "organization/<int:pk>/update/",
        views.OrganizationUpdateView.as_view(),
        name="organization_update",
    ),
    path(
        "organization/<int:orga_pk>/<slug>/events/<int:page>/",
        views.OrganizationEventsListView.as_view(),
        name="organization_all_events",
    ),
    path(
        "organization/<int:pk>/",
        views.OrganizationDeleteView.as_view(),
        name="organization_delete",
    ),
    path(
        "organization/<int:pk>/add-admin",
        views.AddAdminToOrganization.as_view(),
        name="organization_add_admin",
    ),
    path(
        "organization/<int:pk>/add-active",
        views.AddActiveToOrganization.as_view(),
        name="organization_add_active",
    ),
    path(
        "organization/<int:pk>/add-volunteer",
        views.AddVolunteerToOrganization.as_view(),
        name="organization_add_volunteer",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-actives",
        views.RemoveActiveFromOrganization.as_view(),
        name="remove_from_actives",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-volunteers",
        views.RemoveVolunteerFromOrganization.as_view(),
        name="remove_from_volunteers",
    ),
    path(
        "organization/<int:pk>/<int:user_pk>/remove-from-admins",
        views.RemoveAdminFromOrganization.as_view(),
        name="remove_from_admins",
    ),
    path(
        "organization/<int:pk>/add-member",
        CreateMembershipMixin.as_view(),
        name="organization_add_member",
    ),
    path(
        "organization/<int:orga_pk>/update-member/<int:pk>",
        UpdateMembershipMixin.as_view(),
        name="organization_update_member",
    ),
    path(
        "delete-member/<int:pk>", DeleteMembershipMixin.as_view(), name="delete_member"
    ),
    path(
        "fee/<int:pk>/delete/",
        views.FeeDeleteView.as_view(),
        name="fee_delete",
    ),
    path(
        "fee/create/",
        views.FeeCreateView.as_view(),
        name="fee_create",
    )
]

openrepairplatform/event/models.py
from datetime import date, datetime, timedelta

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords

from openrepairplatform.fields import CleanHTMLField

from openrepairplatform.location.models import Place
from openrepairplatform.user.models import CustomUser, Organization
from openrepairplatform.utils import get_future_published_events, validate_image
from openrepairplatform.inventory.models import Stuff


class Condition(models.Model):
    name = models.CharField(verbose_name=_("Condition Type"), max_length=100)
    description = models.CharField(
        verbose_name=_("Condition description"), default="", max_length=300
    )
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="conditions"
    )
    price = models.FloatField(verbose_name=_("Price"), default=5)
    history = HistoricalRecords()

    def get_absolute_url(self):
        return reverse(
            "organization_page",
            kwargs={"orga_slug": self.organization.slug},
        )

    def __str__(self):
        if self.price > 0:
            return f"{self.name} - {self.price}€"
        return self.name


class ActivityCategory(models.Model):
    name = models.CharField(verbose_name=_("Activity type"), max_length=100)
    slug = models.SlugField(blank=True)
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Activity(models.Model):
    name = models.CharField(verbose_name=_("Activity type"), max_length=100)
    category = models.ForeignKey(
        ActivityCategory,
        related_name="category",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    slug = models.SlugField(blank=True)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="activities"
    )
    description = CleanHTMLField(verbose_name=_("Activity description"), default="")
    picture = models.ImageField(
        verbose_name=_("Image"),
        upload_to="activities/",
        blank=True,
        null=True,
        validators=[validate_image],
    )
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("event:activity_detail", args=(self.pk, self.slug))

    def next_events(self):
        return get_future_published_events(self.events)[0:3]

    class Meta:
        verbose_name_plural = 'Activities'

class Event(models.Model):
    WEEKS = [
        (1, "Semaine 1"),
        (2, "Semaine 2"),
        (3, "Semaine 3"),
        (4, "Semaine 4"),
        (5, "Semaine 5"),
    ]
    DAYS = [
        ("MO", "Lundi"),
        ("TU", "Mardi"),
        ("WE", "Mercredi"),
        ("TH", "Jeudi"),
        ("FR", "Vendredi"),
        ("SA", "Samedi"),
        ("SU", "Dimanche"),
    ]

    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="events"
    )
    conditions = models.ManyToManyField(
        Condition,
        related_name="events",
        verbose_name=_("Conditions"),
        blank=True,
    )
    published = models.BooleanField(
        verbose_name=_("Published"),
        default=False,
    )
    publish_at = models.DateTimeField(
        verbose_name=_("Publication date and time"), default=timezone.now
    )
    activity = models.ForeignKey(
        Activity, on_delete=models.SET_NULL, null=True, related_name="events"
    )
    description = CleanHTMLField(
        verbose_name=_(
            "Description supplémentaire de l'événément "
            "(remplace la définition par défaut de l'activité)"
        ),
        blank=True,
    )
    collaborator = models.CharField(
        verbose_name=_("En association avec"), max_length=100, blank=True
    )
    external = models.BooleanField(
        verbose_name=_("Réservation externe au site ?"), default=False
    )
    external_url = models.URLField(
        max_length=200,
        verbose_name=_(
            "Lien vers un site externe. Pour la réservation externe "
            "(si activée) ou simplement pour info"
        ),
        blank=True,
    )
    members_only = models.BooleanField(default=True, blank=True)
    slug = models.SlugField(blank=True)
    date = models.DateField(verbose_name=_("Jour"), default=date.today)
    starts_at = models.TimeField(verbose_name=_("Heure de début"), default=timezone.now)
    ends_at = models.TimeField(verbose_name=_("Heure de fin"))
    available_seats = models.PositiveIntegerField(
        verbose_name=_("Places disponibles"), default=0
    )
    registered = models.ManyToManyField(
        CustomUser,
        related_name="registered_events",
        verbose_name=_("Utilisateurs attendus"),
        blank=True,
    )
    presents = models.ManyToManyField(
        CustomUser,
        related_name="presents_events",
        verbose_name=_("Presents"),
        blank=True,
        through="Participation",
    )
    needed_organizers = models.PositiveIntegerField(
        verbose_name=_("Nombre d'animateurs attendus"), default=0
    )
    organizers = models.ManyToManyField(
        CustomUser,
        related_name="organizers_events",
        verbose_name=_("Organisateurs / animateurs "),
        blank=True,
    )
    location = models.ForeignKey(
        Place,
        on_delete=models.SET_NULL,
        null=True,
        related_name="events",
        verbose_name="Lieu",
    )
    allow_stuffs = models.BooleanField(
        verbose_name=_("Souhaitez-vous gérer des réparations électroniques ?"),
        default=False,
        blank=True,
        help_text=(
            "Les participants pourront déclarer leurs objets électroniques à réparer "
            "lors de la réservation"
        ),
    )
    stuffs = models.ManyToManyField(
        Stuff,
        verbose_name=_("Objets attendus"),
        related_name="events",
        blank=True,
    )
    is_free = models.BooleanField(
        default=False, verbose_name=_("Pas de limite de place ?")
    )
    booking = models.BooleanField(
        default=False, verbose_name=_("Réservation nécessaire ?")
    )
    internal_notes = CleanHTMLField(
        verbose_name= _("Notes de l'évènement visibles en interne"),
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    def save(self, *args, **kwargs):
        if self.activity:
            slug = self.activity.name
        else:
            slug = "no activity type"
        self.slug = slugify(slug)
        return super().save(*args, kwargs)

    @property
    def remaining_seats(self):
        return self.available_seats - self.registered.count()

    def date_interval_format(self):
        date = self.date.strftime("%A %d %B")
        starts_at_time = self.starts_at.strftime("%H:%M")
        ends_at_time = self.ends_at.strftime("%H:%M")

        # ex Lundi 01 Janvier 2018 de 20:01:12 à 22:01:12
        return f"{date} de {starts_at_time} à {ends_at_time}"

    def get_absolute_url(self):
        return reverse("event:detail", args=(self.pk, self.slug))

    @property
    def has_ended(self):
        ends = datetime.combine(
            self.date, self.ends_at, tzinfo=timezone.now().tzinfo
        ) + timedelta(hours=4)
        return ends < timezone.now()

    @property
    def has_started(self):
        starts = datetime.combine(
            self.date, self.starts_at, tzinfo=timezone.now().tzinfo
        ) - timedelta(hours=2)
        return starts < timezone.now()

    @classmethod
    def future_published_events(cls):
        return get_future_published_events(cls.objects)

    def __str__(self):
        if self.activity:
            activity_name = self.activity.name
        else:
            activity_name = "no activity type"
        full_title = "%s du %s" % (
            activity_name,
            self.date.strftime("%d %B"),
        )
        return full_title


class Participation(models.Model):
    PAYMENT_CASH = "1"
    PAYMENT_BANK = "2"
    PAYMENT_BANK_CHECK = "3"
    PAYMENT_CB = "4"
    PAYMENT_LOCAL_CASH = "5"
    PAYMENTS = (
        (PAYMENT_CASH, _("Espèces")),
        (PAYMENT_BANK, _("En ligne")),
        (PAYMENT_BANK_CHECK, _("Chèque")),
        (PAYMENT_CB, _("CB")),
        (PAYMENT_LOCAL_CASH, _("Monnaie locale")),
    )
    payment = models.CharField(
        max_length=1, choices=PAYMENTS, blank=True, default=PAYMENT_CASH
    )
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name="participations"
    )
    amount = models.PositiveIntegerField(
        verbose_name=_("Montant payé"), default=0, blank=True
    )
    history = HistoricalRecords()

    class Meta:
        unique_together = (("user", "event"),)

    def __str__(self):
        return " Participation " + self.user.first_name + " " + str(self.event)

    def get_absolute_url(self):
        return reverse("event:detail", args=(self.event.pk, self.event.slug))

openrepairplatform/user/templates/user/organization/confirmation_delete.html
{% extends 'base.html' %}

{% block content %}
  {% url "user:organization_list" as organization_list_url %}
  {% url "organization_page" organization.pk organization.slug as organization_page_url %}
  {% include "breadcrumb.html" with current="Suppression" second_parent_url=organization_list_url second_parent_text="Organisations" first_parent_url=organization_page_url first_parent_text=organization %}

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h2 class="mt-5">Suppression de '{{ organization }}'</h2>
    </div>
  </div>

  <section class="container">
    <p class="p-2">
      <i class="fa fa-exclamation-triangle"></i>
      Vous êtes sur le point de supprimer l'organisation <code>'{{ organization }}'</code>. Êtes-vous certain de votre choix ?
    </p>
    <form class="p-2" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-danger" type="submit" value="Oui je suis sûr">
    </form>
  </section>
{% endblock %}

openrepairplatform/user/templates/user/organization/modal_more_info.html
{% load static bootstrap5 app_filters static %}

<div class="modal fade" id="more-info-{{ anonymous_user.pk }}" tabindex="-1" data-bs-focus="false" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">

  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
        {% if anonymous_user %}
        Compléter les info de {{ anonymous_user }} 
        {% else %}
        Ajouter un membre à l'organisation
        {% endif %}
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

      </div>
      <div class="modal-body">
        {% if anonymous_user %}
        {% else %}
        {% bootstrap_form search_form %}
          {{search_form.media}}
        {% endif %}
        <form
            {% if anonymous_user %}
            action="{% url 'user:organization_update_member' object.pk anonymous_user.pk %}"
            {% else %}
            action="{% url 'user:organization_add_member' object.pk %}"
            {% endif %}
            method="post"
            class="text-left"
        >
          <div class="modal-body">
            {% csrf_token %}
            {% if anonymous_user %}
            {% bootstrap_form form=form|initial:anonymous_user %}
            {% else %}
            {% bootstrap_form form=form %}
            {% endif %}
          </div>
          {% if object.fee_description %}
            <p>{{ object.fee_description }}</p>
          {% endif %}
          <p>
            <b>Note:</b>
            La contribution minimale pour cette organisation est de
            <span class="badge badge-pill bg-secondary">{{ object.min_fee }}€</span>
            et la contribution totale conseillée est de
            <span class="badge badge-pill bg-success">{{ object.advised_fee }}€</span>
            {% if anonymous_user and anonymous_user.first_name %}
              <br>
              {% filter_orga queryset=anonymous_user.memberships organization=object as membership %}
              {% if membership %}
                {{ anonymous_user }} a payé <span class="badge badge-pill bg-primary">{{ membership.current_contribution }}€</span> depuis le {{ membership.first_payment|date:"d F Y" }}
              {% else %}
                {{ anonymous_user }} n'a pas encore contribué pour <b>{{ object }}</b>
              {% endif %}
            {% endif %}
          </p>
          <div class="modal-footer">
            <input type="submit" value="Enregistrer" class="btn btn-primary">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

openrepairplatform/user/templates/user/organization/organization_card.html
{% load thumbnail %}

{% for organization in organizations %}
<div class="col-4">
  <div class="card text-center h-100">  
    <a class="card-link text-center" href="{% url 'organization_page' organization.slug %}">
      {% if organization.picture %}
      {% thumbnail organization.picture "250" format="PNG" as im %}
        <img class="d-inline" src="{{ im.url }}"/>
      {% endthumbnail %}
      {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{ organization.name }}</h5>
      </div>
    </a>
  </div>
</div>
{% empty %}
  <div>Aucune organisation n'est inscrite sur le site pour le moment</div>
{% endfor %}

openrepairplatform/user/templates/user/organization/organization_event_list.html
{% extends 'base.html' %}
{% block title %}Evénements de {{organisation}} sur {{site_title}}{% endblock %}

{% block content %}
  {% url "user:organization_list" as organization_list_url %}
  {% url "organization_page" organization.slug  as organization_url %}
  {% include "breadcrumb.html" with current="Évènements" first_parent_url=organization_url first_parent_text=organization second_parent_url=organization_list_url second_parent_text="Organisations" %}

  <div class="container">
    <h1 class="mt-4 mb-4 text-center">Tous les évènements liés à {{ organization }}</h1>
    {% if is_paginated %}
      <nav aria-label="Event navigation" class="mt-4">
        <ul class="pagination justify-content-center">
          <li class="page-item{% if paginator.has_previous %} disabled{% endif %}">
            <a class="page-link" href="{% url 'user:organization_all_events' organization.pk organization.slug page_obj.number|add:-1 %}" tabindex="-1">
              Previous
            </a>
          </li>

          {% for page in paginator.page_range %}
            <li class="page-item{% if page == page_obj.number %} active{% endif %}">
              <a class="page-link" href="{% url 'user:organization_all_events' organization.pk organization.slug page %}">
                {{ page }}
              </a>
            </li>
          {% endfor %}

          <li class="page-item{% if paginator.has_next %} disabled{% endif %}">
            <a class="page-link" href="{% url 'user:organization_all_events' organization.pk organization.slug page_obj.number|add:1 %}">
              Next
            </a>
          </li>
        </ul>
      </nav>
    {% endif %}
    <div class="col-lg">
      {% include "event/event_cards.html" with event_list=event_list card_size='col-md-4' %}
    </div>
  </div>
{% endblock %}

openrepairplatform/user/templates/user/organization/organization_form.html
{% extends 'base.html' %}
{% block title %}Créer une organisation sur {{site_title}}{% endblock %}

{% load bootstrap5 %}

{% block content %}
{% url "user:organization_list" as organization_list_url %}
{% if organization %}
  {% url "organization_page" organization.slug as organization_page_url %}
  {% include "breadcrumb.html" with current="Mise à jour" second_parent_url=organization_list_url second_parent_text="Organisations" first_parent_url=organization_page_url first_parent_text=organization %}
{% else %}
  {% include "breadcrumb.html" with current="Création" first_parent_url=organization_list_url first_parent_text="Organisations" %}
{% endif %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>
      Organisation
    </h1>
  </div>
</div>

<div class="container">

  <div class="card p-3">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="form-group p-2">
        <input type="submit" value="Valider" class="btn btn-primary">
      </div>
    </form>
  </div>

</div>
{% endblock %}


{% block extra_js %}
  {{ form.media }}
{% endblock %}

openrepairplatform/user/templates/user/organization/organization_list.html
{% extends "base.html" %}
{% block title %}Découvrez les organisations présentes sur {{ site_title }}
{% endblock title %}


{% block content %}
  {% include "breadcrumb.html" with current="Organisations" %}

  <div class="jumbotron jumbotron-fluid parallax" id="jumbotron">
    <div class="container text-center">
      <h2>Organisations</h2>
      <hr>
      <span>Retrouvez ici les pages des organisations inscrites sur cette plateforme</span>
      {% if user.is_staff %}
      <a class="btn btn-success btn-sm" href="{% url 'user:organization_create' %}">
        <i class="fa fa-pencil-alt me-1"></i>Créer une organisation
      </a>
      {% endif %}
    </div>
  </div>

  <section class="container">
    <div class="row col-md-12 mt-5 mb-5">
      <div class="row g-4 ms-0">
        {% include "user/organization/organization_card.html" with organizations=object_list %}
      </div>
    </div>
  </section>

{% endblock %}

{% block extra_js %}

{% endblock %}